import type { TutorialDefinition } from '@/tutorials/types'
import { ROUTE_NAMES, ROUTE_PATHS } from '@/constants/routes'

export const dashboardTutorial: TutorialDefinition = {
  id: 'dashboard',
  version: 1,
  kind: 'tutorial',
  title: 'Conheça o dashboard',
  description: 'Veja o resumo do dia e os atalhos principais do negócio.',
  estimatedMinutes: 1,
  routeName: ROUTE_NAMES.DASHBOARD_HOME,
  routePath: ROUTE_PATHS.DASHBOARD,
  module: 'Dashboard',
  section: 'Gestão',
  steps: [
    {
      id: 'intro',
      type: 'intro',
      title: 'Seu painel',
      description: 'O dashboard reúne o essencial para acompanhar o dia da loja.',
      interaction: 'blocked',
      allowBack: false,
    },
    {
      id: 'content',
      type: 'info',
      target: '[data-tour="dashboard-page"]',
      title: 'Visão geral',
      description: 'Aqui você encontra indicadores e atalhos para as áreas principais.',
      interaction: 'blocked',
    },
    {
      id: 'completion',
      type: 'completion',
      title: 'Tour concluído',
      description: 'Explore o painel e use os tutoriais de cada módulo quando precisar.',
      interaction: 'blocked',
      allowBack: false,
    },
  ],
}

export const storesTutorial: TutorialDefinition = {
  id: 'stores',
  version: 1,
  kind: 'tutorial',
  title: 'Minhas lojas',
  description: 'Gerencie unidades, troque o estabelecimento ativo e veja limites do plano.',
  estimatedMinutes: 2,
  routeName: ROUTE_NAMES.MINHAS_LOJAS,
  routePath: ROUTE_PATHS.MINHAS_LOJAS,
  module: 'Estabelecimento',
  section: 'Gestão',
  steps: [
    {
      id: 'intro',
      type: 'intro',
      title: 'Suas unidades',
      description: 'Entenda como gerenciar e alternar entre estabelecimentos.',
      interaction: 'blocked',
      allowBack: false,
    },
    {
      id: 'content',
      type: 'info',
      target: '[data-tour="stores-page"]',
      title: 'Lista de lojas',
      description: 'Aqui ficam as unidades da sua conta e a loja atualmente selecionada.',
      interaction: 'blocked',
    },
    {
      id: 'completion',
      type: 'completion',
      title: 'Tour concluído',
      description: 'Você já sabe onde gerenciar suas unidades.',
      interaction: 'blocked',
      allowBack: false,
    },
  ],
}

export const clientsTutorial: TutorialDefinition = {
  id: 'clients',
  version: 1,
  kind: 'tutorial',
  title: 'Clientes',
  description: 'Consulte e organize a base de clientes do estabelecimento.',
  estimatedMinutes: 1,
  routeName: ROUTE_NAMES.CONFIG_CLIENTES,
  routePath: ROUTE_PATHS.CONFIG_CLIENTES,
  module: 'Clientes',
  section: 'Gestão',
  requerModulo: 'Clientes',
  steps: [
    {
      id: 'intro',
      type: 'intro',
      title: 'Seus clientes',
      description: 'Veja quem já agendou e mantenha o relacionamento organizado.',
      interaction: 'blocked',
      allowBack: false,
    },
    {
      id: 'content',
      type: 'info',
      target: '[data-tour="clients-page"]',
      title: 'Base de clientes',
      description: 'Aqui você consulta e gerencia os clientes vinculados à loja.',
      interaction: 'blocked',
    },
    {
      id: 'completion',
      type: 'completion',
      title: 'Tour concluído',
      description: 'Pronto para explorar sua base de clientes.',
      interaction: 'blocked',
      allowBack: false,
    },
  ],
}

export const financeTutorial: TutorialDefinition = {
  id: 'finance',
  version: 1,
  kind: 'tutorial',
  title: 'Financeiro',
  description: 'Acompanhe o resumo financeiro e as movimentações da loja.',
  estimatedMinutes: 2,
  routeName: ROUTE_NAMES.FINANCEIRO,
  routePath: ROUTE_PATHS.FINANCEIRO,
  module: 'Financeiro',
  section: 'Financeiro',
  steps: [
    {
      id: 'intro',
      type: 'intro',
      title: 'Área financeira',
      description: 'Um panorama rápido do caixa e das movimentações.',
      interaction: 'blocked',
      allowBack: false,
    },
    {
      id: 'content',
      type: 'info',
      target: '[data-tour="finance-page"]',
      title: 'Resumo financeiro',
      description: 'Use esta tela para acompanhar o desempenho financeiro do período.',
      interaction: 'blocked',
    },
    {
      id: 'completion',
      type: 'completion',
      title: 'Tour concluído',
      description: 'Explore as abas financeiras conforme a necessidade do dia.',
      interaction: 'blocked',
      allowBack: false,
    },
  ],
}

export const subscriptionTutorial: TutorialDefinition = {
  id: 'subscription',
  version: 1,
  kind: 'tutorial',
  title: 'Assinatura',
  description: 'Veja o plano atual, faturas e opções de upgrade.',
  estimatedMinutes: 1,
  routeName: ROUTE_NAMES.CONFIG_ASSINATURA,
  routePath: ROUTE_PATHS.CONFIG_ASSINATURA,
  module: 'Assinatura',
  section: 'Financeiro',
  requerModulo: 'Assinatura',
  steps: [
    {
      id: 'intro',
      type: 'intro',
      title: 'Sua assinatura',
      description: 'Acompanhe o plano contratado e a situação da cobrança.',
      interaction: 'blocked',
      allowBack: false,
    },
    {
      id: 'content',
      type: 'info',
      target: '[data-tour="subscription-page"]',
      title: 'Plano e cobrança',
      description: 'Aqui ficam o plano atual, status e atalhos para faturas e upgrade.',
      interaction: 'blocked',
    },
    {
      id: 'completion',
      type: 'completion',
      title: 'Tour concluído',
      description: 'Você já sabe onde gerenciar a assinatura.',
      interaction: 'blocked',
      allowBack: false,
    },
  ],
}

export const storeProfileTutorial: TutorialDefinition = {
  id: 'store-profile',
  version: 1,
  kind: 'tutorial',
  title: 'Configure seu estabelecimento',
  description: 'Atualize dados da loja, logo, endereço e link público.',
  estimatedMinutes: 2,
  routeName: ROUTE_NAMES.CONFIG_PERFIL,
  routePath: ROUTE_PATHS.CONFIG_PERFIL,
  module: 'Estabelecimento',
  section: 'Configurações',
  steps: [
    {
      id: 'intro',
      type: 'intro',
      title: 'Perfil da loja',
      description: 'Mantenha as informações do estabelecimento completas e atualizadas.',
      interaction: 'blocked',
      allowBack: false,
    },
    {
      id: 'content',
      type: 'info',
      target: '[data-tour="store-profile-page"]',
      title: 'Dados do estabelecimento',
      description: 'Edite nome, contato, endereço, logo e configurações públicas.',
      interaction: 'blocked',
    },
    {
      id: 'completion',
      type: 'completion',
      title: 'Tour concluído',
      description: 'Seu perfil de loja é o cartão de visita para os clientes.',
      interaction: 'blocked',
      allowBack: false,
    },
  ],
}

export const teamTutorial: TutorialDefinition = {
  id: 'team',
  version: 1,
  kind: 'tutorial',
  title: 'Equipe',
  description: 'Gerencie profissionais, convites e permissões da loja.',
  estimatedMinutes: 2,
  routeName: ROUTE_NAMES.CONFIG_EQUIPE,
  routePath: ROUTE_PATHS.CONFIG_EQUIPE,
  module: 'Profissionais',
  section: 'Configurações',
  requerModulo: 'Profissionais',
  steps: [
    {
      id: 'intro',
      type: 'intro',
      title: 'Sua equipe',
      description: 'Organize quem atende na loja e como cada pessoa acessa o sistema.',
      interaction: 'blocked',
      allowBack: false,
    },
    {
      id: 'content',
      type: 'info',
      target: '[data-tour="team-page"]',
      title: 'Profissionais',
      description: 'Aqui você adiciona, edita e acompanha a equipe do estabelecimento.',
      interaction: 'blocked',
    },
    {
      id: 'completion',
      type: 'completion',
      title: 'Tour concluído',
      description: 'Use esta área sempre que precisar ajustar a equipe.',
      interaction: 'blocked',
      allowBack: false,
    },
  ],
}

export const integrationsTutorial: TutorialDefinition = {
  id: 'integrations',
  version: 1,
  kind: 'tutorial',
  title: 'Integrações',
  description: 'Conecte canais como WhatsApp ao seu estabelecimento.',
  estimatedMinutes: 1,
  routeName: ROUTE_NAMES.CONFIG_WHATSAPP,
  routePath: ROUTE_PATHS.CONFIG_WHATSAPP,
  module: 'WhatsApp',
  section: 'Configurações',
  requerModulo: 'WhatsApp',
  steps: [
    {
      id: 'intro',
      type: 'intro',
      title: 'Integrações',
      description: 'Conecte ferramentas externas para automatizar a comunicação.',
      interaction: 'blocked',
      allowBack: false,
    },
    {
      id: 'content',
      type: 'info',
      target: '[data-tour="integrations-page"]',
      title: 'WhatsApp',
      description: 'Configure a conexão e o status da integração com WhatsApp.',
      interaction: 'blocked',
    },
    {
      id: 'completion',
      type: 'completion',
      title: 'Tour concluído',
      description: 'Volte aqui sempre que precisar revisar a integração.',
      interaction: 'blocked',
      allowBack: false,
    },
  ],
}

export const auditTutorial: TutorialDefinition = {
  id: 'audit',
  version: 1,
  kind: 'tutorial',
  title: 'Auditoria',
  description: 'Acompanhe o histórico de ações relevantes no estabelecimento.',
  estimatedMinutes: 1,
  routeName: ROUTE_NAMES.CONFIG_AUDITORIA,
  routePath: ROUTE_PATHS.CONFIG_AUDITORIA,
  module: 'Auditoria',
  section: 'Configurações',
  steps: [
    {
      id: 'intro',
      type: 'intro',
      title: 'Auditoria',
      description: 'Consulte o registro de eventos importantes da operação.',
      interaction: 'blocked',
      allowBack: false,
    },
    {
      id: 'content',
      type: 'info',
      target: '[data-tour="audit-page"]',
      title: 'Histórico',
      description: 'Os eventos listados ajudam a entender o que aconteceu na loja.',
      interaction: 'blocked',
    },
    {
      id: 'completion',
      type: 'completion',
      title: 'Tour concluído',
      description: 'Use a auditoria para acompanhar mudanças críticas.',
      interaction: 'blocked',
      allowBack: false,
    },
  ],
}

export const preferencesTutorial: TutorialDefinition = {
  id: 'preferences',
  version: 1,
  kind: 'tutorial',
  title: 'Preferências',
  description: 'Ajuste privacidade e preferências da conta.',
  estimatedMinutes: 1,
  routeName: ROUTE_NAMES.CONFIG_PRIVACIDADE,
  routePath: ROUTE_PATHS.CONFIG_PRIVACIDADE,
  module: 'Preferencias',
  section: 'Configurações',
  steps: [
    {
      id: 'intro',
      type: 'intro',
      title: 'Preferências',
      description: 'Gerencie privacidade e opções da sua conta.',
      interaction: 'blocked',
      allowBack: false,
    },
    {
      id: 'content',
      type: 'info',
      target: '[data-tour="preferences-page"]',
      title: 'Configurações',
      description: 'Ajuste consentimentos e preferências conforme sua necessidade.',
      interaction: 'blocked',
    },
    {
      id: 'completion',
      type: 'completion',
      title: 'Tour concluído',
      description: 'Suas preferências estão sob controle.',
      interaction: 'blocked',
      allowBack: false,
    },
  ],
}

export const profileTutorial: TutorialDefinition = {
  id: 'profile',
  version: 1,
  kind: 'tutorial',
  title: 'Seu perfil',
  description: 'Atualize dados pessoais e preferências da conta.',
  estimatedMinutes: 1,
  routeName: ROUTE_NAMES.PERFIL,
  routePath: ROUTE_PATHS.PERFIL,
  module: 'Perfil',
  section: 'Configurações',
  steps: [
    {
      id: 'intro',
      type: 'intro',
      title: 'Perfil',
      description: 'Mantenha seus dados pessoais atualizados.',
      interaction: 'blocked',
      allowBack: false,
    },
    {
      id: 'content',
      type: 'info',
      target: '[data-tour="profile-page"]',
      title: 'Seus dados',
      description: 'Edite nome, contato e outras informações da conta.',
      interaction: 'blocked',
    },
    {
      id: 'completion',
      type: 'completion',
      title: 'Tour concluído',
      description: 'Seu perfil está pronto para uso.',
      interaction: 'blocked',
      allowBack: false,
    },
  ],
}
