import type { TutorialDefinition } from '@/tutorials/types'
import { ROUTE_NAMES, ROUTE_PATHS } from '@/constants/routes'

export const businessHoursTutorial: TutorialDefinition = {
  id: 'business-hours',
  version: 1,
  kind: 'tutorial',
  title: 'Configure seus horários',
  description: 'Defina quando sua loja está disponível e vincule a equipe.',
  estimatedMinutes: 2,
  routeName: ROUTE_NAMES.CONFIG_HORARIOS,
  routePath: ROUTE_PATHS.CONFIG_HORARIOS,
  module: 'HorariosAtendimento',
  section: 'Configurações',
  requerModulo: 'HorariosAtendimento',
  steps: [
    {
      id: 'intro',
      type: 'intro',
      title: 'Conheça seus horários',
      description:
        'Vou mostrar como configurar os horários da sua loja e vincular sua equipe. Leva cerca de 2 minutos.',
      interaction: 'blocked',
      allowBack: false,
    },
    {
      id: 'week-overview',
      type: 'info',
      target: '[data-tour="horarios-week"]',
      title: 'Sua semana',
      description: 'Cada card representa um dia de funcionamento da sua loja.',
      interaction: 'blocked',
    },
    {
      id: 'edit-day',
      type: 'action',
      target: '[data-tour="horario-edit-day"]',
      action: 'click',
      title: 'Configure um dia',
      description: 'Clique em Editar dia ou Definir horário para começar.',
      interaction: 'target-only',
    },
    {
      id: 'times',
      type: 'info',
      target: '[data-tour="horario-times"]',
      title: 'Abertura e fechamento',
      description: 'Defina quando sua loja abre e fecha neste dia.',
      interaction: 'blocked',
    },
    {
      id: 'professionals',
      type: 'action',
      target: '[data-tour="horario-profissionais"]',
      action: 'click',
      title: 'Adicione profissionais',
      description: 'Escolha quem estará disponível para atender neste dia.',
      tip: 'Você pode selecionar mais de um.',
      interaction: 'target-only',
      skipIf: (ctx) => Boolean(ctx.apenasHorarioProprio),
    },
    {
      id: 'save',
      type: 'action',
      target: '[data-tour="horario-save"]',
      action: 'click',
      waitForEvent: 'horario.dia.saved',
      title: 'Salve a configuração',
      description: 'Clique em Salvar. Vamos aguardar a confirmação do sistema.',
      interaction: 'target-only',
    },
    {
      id: 'success',
      type: 'success',
      title: 'Horário configurado',
      description: 'Agora sua loja já tem este dia pronto para receber agendamentos.',
      interaction: 'blocked',
      allowBack: false,
    },
    {
      id: 'completion',
      type: 'completion',
      title: 'Tutorial concluído',
      description: 'Você já sabe como configurar os horários da sua loja.',
      interaction: 'blocked',
      allowBack: false,
    },
  ],
}
