export type NavIconName =
  | 'dashboard'
  | 'home'
  | 'explore'
  | 'calendar'
  | 'invites'
  | 'user'
  | 'store-open'
  | 'services'
  | 'clock'
  | 'team'
  | 'whatsapp'
  | 'finance'
  | 'building'
  | 'subscription'
