import type { RouteRecordRaw } from 'vue-router'
import { ROUTE_NAMES, ROUTE_PATHS } from '@/constants/routes'

export const modulosRoutes: RouteRecordRaw[] = [
  {
    path: ROUTE_PATHS.AGENDA,
    name: ROUTE_NAMES.AGENDA,
    component: () => import('@/views/modulos/agenda/AgendaView.vue'),
    meta: {
      layout: 'dashboard',
      requiresAuth: true,
      businessOnly: true,
      requerModulo: 'Agenda',
      requerPermissoes: ['AgendaVisualizarGeral', 'AgendaVisualizarPropria'],
      permitidoRoleProfissional: true,
      title: 'Agenda',
    },
  },
  {
    path: ROUTE_PATHS.AGENDA_SEMANA,
    name: ROUTE_NAMES.AGENDA_SEMANA,
    component: () => import('@/views/modulos/agenda/AgendaSemanaView.vue'),
    meta: {
      layout: 'dashboard',
      requiresAuth: true,
      businessOnly: true,
      requerModulo: 'Agenda',
      requerPermissoes: ['AgendaVisualizarGeral', 'AgendaVisualizarPropria'],
      permitidoRoleProfissional: true,
      title: 'Agenda — Semana',
    },
  },
  {
    path: ROUTE_PATHS.AGENDA_MES,
    name: ROUTE_NAMES.AGENDA_MES,
    component: () => import('@/views/modulos/agenda/AgendaMesView.vue'),
    meta: {
      layout: 'dashboard',
      requiresAuth: true,
      businessOnly: true,
      requerModulo: 'Agenda',
      requerPermissoes: ['AgendaVisualizarGeral', 'AgendaVisualizarPropria'],
      permitidoRoleProfissional: true,
      title: 'Agenda — Mês',
    },
  },
  {
    path: `${ROUTE_PATHS.AGENDA_DETALHE}/:id`,
    name: ROUTE_NAMES.AGENDA_DETALHE,
    component: () => import('@/views/modulos/agenda/AgendaDetalheView.vue'),
    meta: {
      layout: 'dashboard',
      requiresAuth: true,
      businessOnly: true,
      requerModulo: 'Agenda',
      requerPermissoes: ['AgendaVisualizarGeral', 'AgendaVisualizarPropria'],
      permitidoRoleProfissional: true,
      title: 'Agendamento',
    },
  },
  {
    path: ROUTE_PATHS.SERVICOS,
    name: ROUTE_NAMES.SERVICOS,
    component: () => import('@/views/modulos/servicos/ServicosListView.vue'),
    meta: {
      layout: 'dashboard',
      requiresAuth: true,
      businessOnly: true,
      requerModulo: 'Servicos',
      requerPermissoes: ['ServicoVisualizar', 'ServicoGerenciar'],
      permitidoRoleProfissional: true,
      title: 'Serviços',
    },
  },
  {
    path: ROUTE_PATHS.SERVICOS_NOVO,
    name: ROUTE_NAMES.SERVICOS_NOVO,
    component: () => import('@/views/modulos/servicos/ServicoFormView.vue'),
    meta: {
      layout: 'dashboard',
      requiresAuth: true,
      businessOnly: true,
      requerModulo: 'Servicos',
      requerPermissao: 'ServicoGerenciar',
      title: 'Novo serviço',
    },
  },
  {
    path: `${ROUTE_PATHS.SERVICOS}/:id`,
    name: ROUTE_NAMES.SERVICOS_EDITAR,
    component: () => import('@/views/modulos/servicos/ServicoFormView.vue'),
    meta: {
      layout: 'dashboard',
      requiresAuth: true,
      businessOnly: true,
      requerModulo: 'Servicos',
      requerPermissao: 'ServicoGerenciar',
      title: 'Editar serviço',
    },
  },
  {
    path: `${ROUTE_PATHS.SERVICOS}/:id/profissionais`,
    name: ROUTE_NAMES.SERVICOS_PROFISSIONAIS,
    component: () => import('@/views/modulos/servicos/ServicoProfissionaisView.vue'),
    meta: {
      layout: 'dashboard',
      requiresAuth: true,
      businessOnly: true,
      requerModulo: 'Profissionais',
      requerPermissao: 'ServicoGerenciar',
      title: 'Profissionais do serviço',
    },
  },
  {
    path: ROUTE_PATHS.FINANCEIRO,
    name: ROUTE_NAMES.FINANCEIRO,
    component: () => import('@/views/modulos/financeiro/FinanceiroView.vue'),
    meta: {
      layout: 'dashboard',
      requiresAuth: true,
      businessOnly: true,
      requerModulos: ['Caixa', 'Financeiro'],
      requerPermissao: 'CaixaVisualizar',
      title: 'Financeiro',
    },
  },
  {
    path: ROUTE_PATHS.FINANCEIRO_ENTRADAS,
    name: ROUTE_NAMES.FINANCEIRO_ENTRADAS,
    redirect: (to) => ({
      path: ROUTE_PATHS.FINANCEIRO,
      query: { ...to.query, aba: 'entradas' },
    }),
  },
  {
    path: ROUTE_PATHS.FINANCEIRO_SAIDAS,
    name: ROUTE_NAMES.FINANCEIRO_SAIDAS,
    redirect: (to) => ({
      path: ROUTE_PATHS.FINANCEIRO,
      query: { ...to.query, aba: 'saidas' },
    }),
  },
  {
    path: ROUTE_PATHS.FINANCEIRO_CAIXA,
    redirect: ROUTE_PATHS.FINANCEIRO,
  },
  {
    path: ROUTE_PATHS.FINANCEIRO_MOVIMENTACOES,
    redirect: ROUTE_PATHS.FINANCEIRO,
  },
  {
    path: ROUTE_PATHS.FINANCEIRO_CONTAS,
    redirect: (to) => {
      if (to.query.aba === 'pagar') {
        return { path: ROUTE_PATHS.FINANCEIRO, query: { aba: 'saidas', status: 'pendente' } }
      }
      return { path: ROUTE_PATHS.FINANCEIRO, query: { aba: 'entradas', status: 'pendente' } }
    },
  },
  {
    path: ROUTE_PATHS.FINANCEIRO_COMISSOES,
    name: ROUTE_NAMES.FINANCEIRO_COMISSOES,
    component: () => import('@/views/modulos/financeiro/ComissoesView.vue'),
    meta: {
      layout: 'dashboard',
      requiresAuth: true,
      businessOnly: true,
      requerModulo: 'ComissaoProfissionais',
      requerPermissao: 'CaixaVisualizar',
      title: 'Comissões',
    },
  },
  {
    path: ROUTE_PATHS.FINANCEIRO_METAS,
    redirect: () => ({ path: ROUTE_PATHS.FINANCEIRO_COMISSOES, query: { aba: 'metas' } }),
  },
  {
    path: ROUTE_PATHS.FINANCEIRO_RELATORIOS,
    redirect: ROUTE_PATHS.FINANCEIRO,
  },
  {
    path: ROUTE_PATHS.FINANCEIRO_CONCILIACAO,
    name: ROUTE_NAMES.FINANCEIRO_CONCILIACAO,
    component: () => import('@/views/modulos/financeiro/ConciliacaoView.vue'),
    meta: {
      layout: 'dashboard',
      requiresAuth: true,
      businessOnly: true,
      requerModulo: 'Financeiro',
      requerPermissao: 'CaixaVisualizar',
      title: 'Conciliação',
    },
  },
  {
    path: ROUTE_PATHS.FINANCEIRO_REDE,
    name: ROUTE_NAMES.FINANCEIRO_REDE,
    component: () => import('@/views/modulos/financeiro/RedeView.vue'),
    meta: {
      layout: 'dashboard',
      requiresAuth: true,
      businessOnly: true,
      requerModulo: 'Financeiro',
      requerPermissao: 'CaixaVisualizar',
      title: 'Painel da rede',
    },
  },
  {
    path: ROUTE_PATHS.FINANCEIRO_MINHAS_COMISSOES,
    redirect: ROUTE_PATHS.FINANCEIRO_COMISSOES,
  },
  {
    path: ROUTE_PATHS.FINANCEIRO_CONTAS_RECEBER,
    redirect: { path: ROUTE_PATHS.FINANCEIRO, query: { aba: 'entradas', status: 'pendente' } },
  },
  {
    path: ROUTE_PATHS.FINANCEIRO_CONTAS_PAGAR,
    redirect: { path: ROUTE_PATHS.FINANCEIRO, query: { aba: 'saidas', status: 'pendente' } },
  },
  {
    path: ROUTE_PATHS.CONFIG_EQUIPE,
    name: ROUTE_NAMES.CONFIG_EQUIPE,
    component: () => import('@/views/modulos/equipe/EquipeView.vue'),
    meta: {
      layout: 'dashboard',
      requiresAuth: true,
      businessOnly: true,
      requerModulo: 'Profissionais',
      requerPermissao: 'EquipeGerenciar',
      title: 'Equipe',
    },
  },
  {
    path: ROUTE_PATHS.CONFIG_EQUIPE_CONVITES,
    name: ROUTE_NAMES.CONFIG_EQUIPE_CONVITES,
    component: () => import('@/views/modulos/equipe/EquipeConvitesView.vue'),
    meta: {
      layout: 'dashboard',
      requiresAuth: true,
      businessOnly: true,
      requerModulo: 'Profissionais',
      requerPermissao: 'EquipeGerenciar',
      title: 'Convites da equipe',
    },
  },
  {
    path: ROUTE_PATHS.CONFIG_EQUIPE_USUARIO_NOVO,
    name: ROUTE_NAMES.CONFIG_EQUIPE_USUARIO_NOVO,
    component: () => import('@/views/modulos/equipe/EquipeUsuarioNovoView.vue'),
    meta: {
      layout: 'dashboard',
      requiresAuth: true,
      businessOnly: true,
      requerModulo: 'Profissionais',
      requerPermissao: 'EquipeGerenciar',
      title: 'Adicionar usuário',
    },
  },
  {
    path: ROUTE_PATHS.CONFIG_EQUIPE_NOVO,
    name: ROUTE_NAMES.CONFIG_EQUIPE_NOVO,
    component: () => import('@/views/modulos/equipe/EquipeNovoView.vue'),
    meta: {
      layout: 'dashboard',
      requiresAuth: true,
      businessOnly: true,
      requerModulo: 'Profissionais',
      requerPermissao: 'ProfissionalConvidar',
      title: 'Convidar profissional',
    },
  },
  {
    path: ROUTE_PATHS.CONFIG_WHATSAPP,
    name: ROUTE_NAMES.CONFIG_WHATSAPP,
    component: () => import('@/views/modulos/whatsapp/WhatsAppEstabelecimentoView.vue'),
    meta: {
      layout: 'dashboard',
      requiresAuth: true,
      businessOnly: true,
      requerModulo: 'WhatsApp',
      requerPermissao: 'NegocioEditar',
      title: 'WhatsApp',
    },
  },
  {
    path: ROUTE_PATHS.CONFIG_HORARIOS,
    name: ROUTE_NAMES.CONFIG_HORARIOS,
    component: () => import('@/views/modulos/horarios/HorariosView.vue'),
    meta: {
      layout: 'dashboard',
      requiresAuth: true,
      businessOnly: true,
      requerModulo: 'HorariosAtendimento',
      requerPermissoes: ['HorarioGerenciar', 'HorarioGerenciarProprio'],
      permitidoRoleProfissional: true,
      title: 'Horários',
    },
  },
  {
    path: ROUTE_PATHS.CONFIG_PROFISSIONAIS_VITRINE,
    name: ROUTE_NAMES.CONFIG_PROFISSIONAIS_VITRINE,
    component: () => import('@/views/modulos/profissionais/ProfissionaisVitrineView.vue'),
    meta: {
      layout: 'dashboard',
      requiresAuth: true,
      businessOnly: true,
      requerModulo: 'HorariosAtendimento',
      requerSemModulo: 'Profissionais',
      requerPermissao: 'ProfissionalGerenciar',
      title: 'Profissionais',
    },
  },
  {
    path: ROUTE_PATHS.CONFIG_PERFIL,
    name: ROUTE_NAMES.CONFIG_PERFIL,
    component: () => import('@/views/modulos/perfil/PerfilEstabelecimentoView.vue'),
    meta: {
      layout: 'dashboard',
      requiresAuth: true,
      businessOnly: true,
      requerModulo: 'Estabelecimento',
      requerPermissao: 'NegocioEditar',
      requerAssinaturaAtiva: false,
      title: 'Perfil do estabelecimento',
    },
  },
  {
    path: ROUTE_PATHS.CONFIG_CLIENTES,
    name: ROUTE_NAMES.CONFIG_CLIENTES,
    component: () => import('@/views/modulos/clientes/ClientesView.vue'),
    meta: {
      layout: 'dashboard',
      requiresAuth: true,
      businessOnly: true,
      requerModulo: 'Clientes',
      requerPermissao: 'ClienteVisualizarGeral',
      title: 'Clientes',
    },
  },
]
