import type { TutorialDefinition } from '@/tutorials/types'
import { ROUTE_NAMES, ROUTE_PATHS } from '@/constants/routes'

/** Missão: cadastrar o primeiro serviço (lista → form → API). */
export const firstServiceMission: TutorialDefinition = {
  id: 'first-service',
  version: 1,
  kind: 'mission',
  title: 'Cadastre seu primeiro serviço',
  description: 'Crie um serviço completo para seus clientes agendarem.',
  estimatedMinutes: 3,
  routeName: ROUTE_NAMES.SERVICOS,
  routePath: ROUTE_PATHS.SERVICOS,
  module: 'Servicos',
  section: 'Gestão',
  requerModulo: 'Servicos',
  requerPermissao: 'ServicoGerenciar',
  steps: [
    {
      id: 'intro',
      type: 'intro',
      title: 'Seu primeiro serviço',
      description:
        'Vou te guiar para cadastrar um serviço com nome, preço e duração. Leva cerca de 3 minutos.',
      interaction: 'blocked',
      allowBack: false,
    },
    {
      id: 'list',
      type: 'info',
      target: '[data-tour="servicos-page"]',
      title: 'Lista de serviços',
      description: 'Aqui ficam todos os serviços disponíveis para agendamento.',
      interaction: 'blocked',
    },
    {
      id: 'create',
      type: 'action',
      target: '[data-tour="servicos-novo"]',
      action: 'click',
      title: 'Sua vez',
      description: 'Clique em Novo serviço para começar o cadastro.',
      interaction: 'target-only',
    },
    {
      id: 'name',
      type: 'input',
      target: '[data-tour="servico-nome"]',
      action: 'input',
      title: 'Nome do serviço',
      description: 'Informe o nome que seus clientes verão ao agendar.',
      interaction: 'target-only',
    },
    {
      id: 'price-duration',
      type: 'info',
      target: '[data-tour="servico-preco-duracao"]',
      title: 'Preço e duração',
      description: 'Defina o valor base e quanto tempo o atendimento leva.',
      interaction: 'free',
    },
    {
      id: 'type',
      type: 'info',
      target: '[data-tour="servico-tipo"]',
      title: 'Tipo do serviço',
      description: 'Escolha se é um atendimento individual ou um pacote.',
      interaction: 'free',
    },
    {
      id: 'professionals',
      type: 'info',
      target: '[data-tour="servico-profissionais"]',
      title: 'Profissionais',
      description: 'Opcional: vincule quem pode realizar este serviço.',
      interaction: 'free',
      skipIf: (ctx) => !ctx.possuiModulo('Profissionais'),
    },
    {
      id: 'save',
      type: 'action',
      target: '[data-tour="servico-save"]',
      action: 'click',
      waitForEvent: 'servico.created',
      title: 'Salve o serviço',
      description: 'Clique em salvar. Vamos aguardar a confirmação do sistema.',
      interaction: 'target-only',
    },
    {
      id: 'success',
      type: 'success',
      title: 'Serviço cadastrado',
      description: 'Agora seus clientes poderão selecioná-lo durante um agendamento.',
      interaction: 'blocked',
      allowBack: false,
    },
    {
      id: 'completion',
      type: 'completion',
      title: 'Missão concluída',
      description: 'Você já sabe como cadastrar serviços no Glow Up.',
      interaction: 'blocked',
      allowBack: false,
    },
  ],
}

/** Tutorial curto da listagem (quando já existem serviços). */
export const servicesTutorial: TutorialDefinition = {
  id: 'services',
  version: 1,
  kind: 'tutorial',
  title: 'Conheça seus serviços',
  description: 'Entenda a lista, o status e como editar um serviço.',
  estimatedMinutes: 1,
  routeName: ROUTE_NAMES.SERVICOS,
  routePath: ROUTE_PATHS.SERVICOS,
  module: 'Servicos',
  section: 'Gestão',
  requerModulo: 'Servicos',
  steps: [
    {
      id: 'intro',
      type: 'intro',
      title: 'Conheça seus serviços',
      description: 'Uma visão rápida da tela de serviços do estabelecimento.',
      interaction: 'blocked',
      allowBack: false,
    },
    {
      id: 'list',
      type: 'info',
      target: '[data-tour="servicos-page"]',
      title: 'Seus serviços',
      description: 'Aqui ficam os serviços disponíveis para seus clientes.',
      interaction: 'blocked',
    },
    {
      id: 'novo',
      type: 'info',
      target: '[data-tour="servicos-novo"]',
      title: 'Novo serviço',
      description: 'Use este botão sempre que quiser cadastrar um novo item.',
      interaction: 'blocked',
      skipIf: (ctx) => !ctx.possuiPermissao('ServicoGerenciar'),
    },
    {
      id: 'completion',
      type: 'completion',
      title: 'Tutorial concluído',
      description: 'Pronto. Explore a lista ou inicie a missão de cadastrar um serviço.',
      interaction: 'blocked',
      allowBack: false,
    },
  ],
}
